version: '3'
services:
  redis:
    image: redis
    ports:
      - 6379:6379

  flask-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 5000:5000
    depends_on:
      - redis